Feature/add l18 for translate
mykhalenych/UseeSvit pull request #19
Opened 2023-06-27 17:11 UTC by barantarasNEW

2023-06-27 19:56 UTC, nosovandriy approved these changes

2023-06-27 20:02 UTC, NataliiaRodoman approved these changes

2023-06-28 03:34 UTC, vanyachyzh approved these changes

2023-06-28 07:48 UTC, mykhalenych requested changes

2023-06-28 07:48 UTC, mykhalenych commented on client/public/locales/en/translation.json
> +    "btn": "LOGIN"
don't use upperCase

2023-06-28 07:48 UTC, mykhalenych commented on client/public/locales/en/translation.json
> +}
<img width="134" alt="Screenshot 2023-06-28 at 10 44 49" src="https://github.com/mykhalenych/someName/assets/53228259/5a10e69a-9fb1-4d57-8620-f15d5a23f0fb">
add empty line in the end of the file

2023-06-28 07:48 UTC, mykhalenych commented on client/public/locales/uk/translation.json
> +  "emailAddress": "Ел. пошта",
```suggestion
  "emailAddress": "Електронна пошта",
```

2023-06-28 07:48 UTC, mykhalenych commented on client/src/common/i18n.ts
> +// eslint-disable-next-line prettier/prettier, import/no-named-as-default-member
```suggestion
```

2023-06-28 07:48 UTC, mykhalenych commented on client/src/common/i18n.ts
> +import i18n from 'i18next';
```suggestion
// eslint-disable import/no-named-as-default-member
import i18n from 'i18next';
```

2023-06-28 07:48 UTC, mykhalenych commented on client/src/index.tsx
> +
```suggestion
```

2023-06-28 07:48 UTC, mykhalenych commented on client/src/services/common.ts
>  import type {AxiosResponse, Method} from 'axios';
```suggestion
import type {AxiosResponse, Method} from 'axios';

```

2023-06-28 07:48 UTC, mykhalenych commented on client/src/services/common.ts
```suggestion
```

2023-06-28 11:46 UTC, nosovandriy approved these changes

2023-06-29 11:18 UTC, NataliiaRodoman approved these changes

2023-06-29 12:23 UTC, mykhalenych approved these changes

2023-06-29 12:23 UTC, merged