feature/reset-password-page add layout, route, thunk, api
mykhalenych/UseeSvit pull request #22
Opened 2023-06-29 08:33 UTC by nosovandriy

add layout, route, thunk, api

2023-06-29 11:20 UTC, vanyachyzh approved these changes

2023-06-29 12:24 UTC, NataliiaRodoman approved these changes

2023-06-30 06:58 UTC, mykhalenych requested changes

2023-06-30 06:58 UTC, mykhalenych commented on server/src/index.js
> +sequelize.sync({force: true});
revert changes

2023-06-30 07:56 UTC, mykhalenych approved these changes

2023-06-30 07:57 UTC, merged