Feature/loader added Created Spinner and added check if isLoading
mykhalenych/UseeSvit pull request #31
Opened 2023-07-06 15:46 UTC by NataliiaRodoman

2023-07-09 08:53 UTC, barantarasNEW approved these changes

2023-07-09 11:03 UTC, nosovandriy requested changes

2023-07-09 11:03 UTC, nosovandriy commented on src/components/common/Button/Button.tsx
> +// }
Remove commented lines

2023-07-10 04:36 UTC, vanyachyzh approved these changes

2023-07-13 11:36 UTC, mykhalenych requested changes

2023-07-13 11:36 UTC, mykhalenych commented on src/components/common/loader/Styles.ts
> +    backgroundColor: theme.palette.primary.main,
delete this

2023-07-13 11:36 UTC, mykhalenych commented on src/layouts/MainLayout/Styles.ts
> +    position: 'relative',
delete display and position here

2023-07-13 11:36 UTC, mykhalenych commented on src/pages/Auth/Activation/Activation.tsx
> +                <Typography variant="h3">{isLoading ? <Progress /> : t('welcomeToUseeSvit')}</Typography>
why it is in Typography?

2023-07-14 06:15 UTC, mykhalenych requested changes

2023-07-14 06:15 UTC, mykhalenych commented on src/components/common/loader/Progress.tsx
> +import React, {useEffect} from 'react';
```suggestion
import React, {useEffect, useState} from 'react';
```

2023-07-14 06:15 UTC, mykhalenych commented on src/components/common/loader/Progress.tsx
> +    const [level, setLevel] = React.useState(0);
```suggestion
    const [level, setLevel] = useState(0);
```

2023-07-14 07:16 UTC, mykhalenych approved these changes

2023-07-14 07:16 UTC, merged