Features/added translation for all errors success notification also for validation messsages
mykhalenych/UseeSvit pull request #33
Opened 2023-07-09 08:36 UTC by barantarasNEW

2023-07-09 10:59 UTC, nosovandriy requested changes

2023-07-09 10:59 UTC, nosovandriy commented on public/locales/ua/notification.json
> +  "passwordHasBeenReset": "Your password has been reset!",
Change to the Ukrainian translation

2023-07-09 10:59 UTC, nosovandriy commented on public/locales/ua/notification.json
> +  "loggedIn": "Ви увійшли в систему!",
In signedIn and logedIn use 'ввійшли' or 'увійшли'

2023-07-10 04:38 UTC, vanyachyzh approved these changes

2023-07-10 06:19 UTC, mykhalenych requested changes

2023-07-10 06:19 UTC, mykhalenych commented on src/redux/auth/thunks.ts
> +                    i18n.t('passwordChangedSuccessfully', {ns: 'notification'}),
add i18.t once inside handle response
i18n.t(message, {ns: 'notification'})

2023-07-12 06:15 UTC, merged